/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.calcados.views;


import com.mycompany.calcados.classes.Produtos;
import com.mycompany.calcados.dao.ProdutosDAO;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kayla
 */
public class CadastroProduto extends javax.swing.JFrame {

    /**
     * Creates new form CadastroProduto
     */
    public CadastroProduto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtcod = new javax.swing.JLabel();
        txtCodProd = new javax.swing.JTextField();
        txtmarca = new javax.swing.JLabel();
        txtmodelo = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtTamanho = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtPreco = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProduto = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtCor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnInserir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        cboMarca = new javax.swing.JComboBox<>();
        cboGenero = new javax.swing.JComboBox<>();
        jbnBusca = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        spnQtd = new javax.swing.JSpinner();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuClientes = new javax.swing.JMenu();
        mnuCadastroCliente = new javax.swing.JMenuItem();
        mnuCarrinho = new javax.swing.JMenuItem();
        mnuProdutos = new javax.swing.JMenu();
        mnuCadastroProduto = new javax.swing.JMenuItem();
        mnuRelatorios = new javax.swing.JMenuItem();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtcod.setText("Código do Produto");

        txtCodProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodProdActionPerformed(evt);
            }
        });
        txtCodProd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodProdKeyTyped(evt);
            }
        });

        txtmarca.setText("Marca");

        txtmodelo.setText("Modelo");

        jLabel6.setText("Genero");

        jLabel7.setText("Tamanho");

        jLabel8.setText("Preço");

        tblProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod Produto", "Marca", "Modelo", "Cor", "Genero", "Tamanho", "Preço", "Qtd"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblProduto);

        jLabel3.setText("Cor");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tenis.jpg"))); // NOI18N

        btnInserir.setText("Inserir");
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        cboMarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione uma opção", "Adidas", "All Star", "Mizuno", "Nike", "Olympikus", "Puma", "Reebok", "Tesla", "Vans" }));

        cboGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione uma opção", "Feminino", "Masculino", "Unissex" }));

        jbnBusca.setText("Buscar");
        jbnBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnBuscaActionPerformed(evt);
            }
        });

        jLabel4.setText("Qtd");

        jMenuBar1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CADASTRO DE PRODUTOS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Rounded MT Bold", 0, 12))); // NOI18N

        mnuClientes.setText("Clientes");

        mnuCadastroCliente.setText("Cadatro de Cliente");
        mnuCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadastroClienteActionPerformed(evt);
            }
        });
        mnuClientes.add(mnuCadastroCliente);

        mnuCarrinho.setText("Carrinho");
        mnuCarrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCarrinhoActionPerformed(evt);
            }
        });
        mnuClientes.add(mnuCarrinho);

        jMenuBar1.add(mnuClientes);

        mnuProdutos.setText("Produtos");

        mnuCadastroProduto.setText("Cadastro de Produto");
        mnuCadastroProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadastroProdutoActionPerformed(evt);
            }
        });
        mnuProdutos.add(mnuCadastroProduto);

        mnuRelatorios.setText("Relatórios");
        mnuRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRelatoriosActionPerformed(evt);
            }
        });
        mnuProdutos.add(mnuRelatorios);

        jMenuBar1.add(mnuProdutos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtcod)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtCodProd, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                                        .addComponent(jbnBusca))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel7)
                                                    .addComponent(jLabel6)
                                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtmodelo)
                                                    .addComponent(txtmarca))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(cboMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtCor, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(cboGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(spnQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(195, 195, 195)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 374, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCodProd, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbnBusca)
                            .addComponent(txtcod))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtmarca)
                            .addComponent(cboMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmodelo))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cboGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel4)
                            .addComponent(spnQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(19, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
       LocalDate localdata = LocalDate.now(); // Obtém a data atual sem o horário
       Date data = java.sql.Date.valueOf(localdata);
       
       // Guardo o valor em variaveis para passar ao meu obj
       int CodProd      = Integer.parseInt(txtCodProd.getText());
       int Tamanho      = Integer.parseInt(txtTamanho.getText());
       double preco     = Double.parseDouble(txtPreco.getText());
       String Modelo    = txtModelo.getText();
       String Cor       = txtCor.getText();
       int qtd     = (int) spnQtd.getValue();
       
       String Marca = cboMarca.getSelectedItem().toString();
       String Genero = cboGenero.getSelectedItem().toString();
       
       if(Marca == "Selecione uma opção" || Genero == "Selecione uma opção"){
           if(Marca == "Selecione uma opção"){
               JOptionPane.showMessageDialog(null, "Selecione uma opção de Marca");
           }else{
               JOptionPane.showMessageDialog(null, "Selecione uma opção de Genero");
           }
       }else if(qtd == 0 || preco == 0 || Tamanho == 0){
           if(qtd == 0){
               JOptionPane.showMessageDialog(null, "Preencha a quantidade de produtos!");
           }else if(Tamanho == 0){
               JOptionPane.showMessageDialog(null, "Especifique o tamanho do produtos!");
           }else{
               JOptionPane.showMessageDialog(null, "Digite o preço do produto!");
           }
       }else if(Modelo.isEmpty() || Cor.isEmpty()){
           if(Modelo.isEmpty()){
               JOptionPane.showMessageDialog(null, "Preencha o modelo do produto!");
           }else{
               JOptionPane.showMessageDialog(null, "Preencha a cor do produto!!");
           }
       }else{
            Produtos CadProdutos = new Produtos(CodProd, preco, Tamanho, Modelo, Marca, Cor, Genero, data, qtd);
            boolean RetornoP = ProdutosDAO.cadastrarP(CadProdutos);
       
            if (RetornoP) {
                JOptionPane.showMessageDialog(null, "Cadastro efetuado com sucesso!");
                txtCodProd.setText("");
                txtTamanho.setText("");
                txtPreco.setText("");
                txtModelo.setText("");
                txtCor.setText("");
                spnQtd.setValue(0);
                cboMarca.setSelectedItem("Selecione uma opção");
                cboGenero.setSelectedItem("Selecione uma opção");

            } else {
                JOptionPane.showMessageDialog(null, "Erro ao fazer salvar o cadastro!");
            }
        }
    }//GEN-LAST:event_btnInserirActionPerformed

    private void txtCodProdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodProdKeyTyped
           char c =evt.getKeyChar();
        
            // se for qualquer tecla diferente de a 9 e backspace
            if((c<'0' || c>'9') && (c != KeyEvent.VK_BACK_SPACE)){
                evt.consume();
                JOptionPane.showMessageDialog(this,"Digite apenas números no Codigo do Produto");
        }
            
        if(txtCodProd.getText().length()>4){
            evt.consume();
            JOptionPane.showMessageDialog(this,"Máximo de 5 caracteres no Codigo do Produto");
        }
    }//GEN-LAST:event_txtCodProdKeyTyped

    private void txtCodProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodProdActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int linhaSele = tblProduto.getSelectedRow();
  
        DefaultTableModel modeloProd = (DefaultTableModel) tblProduto.getModel();
        
        if(linhaSele != -1){
            String id = tblProduto.getValueAt(linhaSele, 0).toString();
            int Id    = Integer.parseInt(id);
            
            boolean RetornoP = ProdutosDAO.excluirP(Id);


            if(RetornoP){
                 modeloProd.removeRow(linhaSele);
            }
            else{
                JOptionPane.showMessageDialog(this,"Selecione uma linha!");
            }
        }else{
            JOptionPane.showMessageDialog(this, "Selecione uma linha!");
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void mnuCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadastroClienteActionPerformed
        CadastroCliente janela = new CadastroCliente();
        janela.setVisible(true);
        
    }//GEN-LAST:event_mnuCadastroClienteActionPerformed

    private void mnuCarrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCarrinhoActionPerformed
        Carrinho janela = new Carrinho();
        janela.setVisible(true);
        
    }//GEN-LAST:event_mnuCarrinhoActionPerformed

    private void mnuCadastroProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadastroProdutoActionPerformed
        CadastroProduto janela = new CadastroProduto();
        janela.setVisible(true);
        
    }//GEN-LAST:event_mnuCadastroProdutoActionPerformed

    private void mnuRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRelatoriosActionPerformed
        Relatorios janela = new Relatorios();
        janela.setVisible(true);
        
    }//GEN-LAST:event_mnuRelatoriosActionPerformed

    private void jbnBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnBuscaActionPerformed
        // Puxando o id como string para verificar se está vazio
        String codText = txtCodProd.getText();
        int cod = codText.isBlank() ? 0 : Integer.parseInt(codText);
        String Marca = cboMarca.getSelectedItem().toString();
       
        if(cod != 0){
            ArrayList<Produtos> listarBuscaP = ProdutosDAO.listarID(cod);

            DefaultTableModel prod = (DefaultTableModel)tblProduto.getModel();
            // Limpo a tabela
            prod.setRowCount(0);

            for(Produtos item : listarBuscaP){
                
                prod.addRow(new String[]{String.valueOf(item.getCod_prod()),
                                         String.valueOf(item.getMarca()),
                                         String.valueOf(item.getModelo()),
                                         String.valueOf(item.getCor()),
                                         String.valueOf(item.getGenero()),
                                         String.valueOf(item.getTamanho()),
                                         String.valueOf(item.getPreco()),
                                         String.valueOf(item.getQtd())
                });
            }
        }else if(!"Selecione uma opção".equals(Marca)){
             ArrayList<Produtos> listarP = ProdutosDAO.listarMarca(Marca);

            DefaultTableModel prod = (DefaultTableModel)tblProduto.getModel();
            // Limpo a tabela
            prod.setRowCount(0);

            for(Produtos item : listarP){
                prod.addRow(new String[]{String.valueOf(item.getCod_prod()),
                                         String.valueOf(item.getMarca()),
                                         String.valueOf(item.getModelo()),
                                         String.valueOf(item.getCor()),
                                         String.valueOf(item.getGenero()),
                                         String.valueOf(item.getTamanho()),
                                         String.valueOf(item.getPreco()),
                                         String.valueOf(item.getQtd())
                });
            }
        }else{
             ArrayList<Produtos> listarBuscaP = ProdutosDAO.listarP();

            DefaultTableModel prod = (DefaultTableModel)tblProduto.getModel();
            // Limpo a tabela
            prod.setRowCount(0);

            for(Produtos item : listarBuscaP){
                prod.addRow(new String[]{String.valueOf(item.getCod_prod()),
                                         String.valueOf(item.getMarca()),
                                         String.valueOf(item.getModelo()),
                                         String.valueOf(item.getCor()),
                                         String.valueOf(item.getGenero()),
                                         String.valueOf(item.getTamanho()),
                                         String.valueOf(item.getPreco()),
                                         String.valueOf(item.getQtd())
                });
            }
        }

               
    }//GEN-LAST:event_jbnBuscaActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
       LocalDate localdata = LocalDate.now(); // Obtém a data atual sem o horário
       Date data = java.sql.Date.valueOf(localdata);
       // modificando para o formato dd/mm/yyyy
       SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
       String dataFor = dateFormat.format(data); 
       int linhaSele  = tblProduto.getSelectedRow();
       
       DefaultTableModel modeloP = (DefaultTableModel) tblProduto.getModel();
 
       // pegando os valores das colunas
       String cod = tblProduto.getValueAt(linhaSele,0).toString();
       String marca = tblProduto.getValueAt(linhaSele,1).toString();
       String modelo = tblProduto.getValueAt(linhaSele,2).toString();
       String cor = tblProduto.getValueAt(linhaSele,3).toString();
       String genero = tblProduto.getValueAt(linhaSele,4).toString();
       String tamanho = tblProduto.getValueAt(linhaSele,5).toString();
       String preco = tblProduto.getValueAt(linhaSele,6).toString();
       String Qtd = tblProduto.getValueAt(linhaSele,7).toString();
        
       int qtd  = Integer.parseInt(Qtd);
       int Cod  = Integer.parseInt(cod);
       int Tamanho  = Integer.parseInt(tamanho);
       double Preco  = Double.parseDouble(preco);
        
       //String Valor = tblClientes.getValueAt(linhaSelecionada,colunaSelecionada).toString();
        
       Produtos prodAlter = new Produtos();
       prodAlter.setCod_prod(Cod);
       prodAlter.setPreco(Preco);
       prodAlter.setTamanho(Tamanho);
       prodAlter.setModelo(modelo);
       prodAlter.setMarca(marca);
       prodAlter.setCor(cor);
       prodAlter.setGenero(genero);
       prodAlter.setData(data);
       prodAlter.setQtd(qtd);
       
       boolean RetornoP = ProdutosDAO.alterarP(prodAlter);
        
        if(RetornoP){
            // remove a linha da tabela
            modeloP.removeRow(linhaSele);
            JOptionPane.showMessageDialog(rootPane, "Alterado com sucesso!");
            
        }else{
              JOptionPane.showMessageDialog(rootPane, "Falha ao alterar!");
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnInserir;
    private javax.swing.JComboBox<String> cboGenero;
    private javax.swing.JComboBox<String> cboMarca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbnBusca;
    private javax.swing.JMenuItem mnuCadastroCliente;
    private javax.swing.JMenuItem mnuCadastroProduto;
    private javax.swing.JMenuItem mnuCarrinho;
    private javax.swing.JMenu mnuClientes;
    private javax.swing.JMenu mnuProdutos;
    private javax.swing.JMenuItem mnuRelatorios;
    private javax.swing.JSpinner spnQtd;
    private javax.swing.JTable tblProduto;
    private javax.swing.JTextField txtCodProd;
    private javax.swing.JTextField txtCor;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JTextField txtTamanho;
    private javax.swing.JLabel txtcod;
    private javax.swing.JLabel txtmarca;
    private javax.swing.JLabel txtmodelo;
    // End of variables declaration//GEN-END:variables
}

